# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: fintech
data:
  application.yml: |-
    spring:
      application:
        name: auth-service
      
      datasource:
        url: jdbc:mysql://terraform-20250112133601126400000001.c122egeymo28.us-east-1.rds.amazonaws.com:3306/auth_service
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
          maximum-pool-size: 10
          minimum-idle: 5
          pool-name: MySQLPool
      
      jpa:
        hibernate:
          ddl-auto: validate
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            format_sql: true
      
      config:
        import: optional:configserver:http://config-server.fintech.svc.cluster.local:8889
      
      eureka:
        client:
          serviceUrl:
            defaultZone: http://discovery-service.fintech.svc.cluster.local:8761/eureka/
          register-with-eureka: true
          fetch-registry: true
        instance:
          prefer-ip-address: true
    
    server:
      port: 8946