apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deploy
  namespace: fintech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: public.ecr.aws/z1z0w2y6/auth-service:latest
          ports:
            - containerPort: 8946
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          envFrom:
            - configMapRef:
                name: auth-service-config
          env:
            - name: SPRING_CONFIG_LOCATION
              value: file:/app/config/application.yml
            # Database credentials
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: password
            # JWT credentials
            - name: SPRING_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-credentials
                  key: jwt-secret
            - name: SPRING_JWT_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  name: jwt-credentials
                  key: jwt-expiration
          resources:
            requests:
              memory: "200Mi"
              cpu: "100m"
            limits:
              memory: "400Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8946
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: auth-service-config
