apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deploy
  namespace: fintech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: public.ecr.aws/z1z0w2y6/auth-service:latest
        ports:
        - containerPort: 8946
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-Xms256m -Xmx384m -XX:+UseContainerSupport"
        - name: SPRING_CONFIG_LOCATION
          value: file:/app/config/application.yml
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://my-database-instance.c122egeymo28.us-east-1.rds.amazonaws.com:3306/auth_service"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
        - name: SPRING_JWT_SECRET
          value: "6f872872a7e1dde2431f5f3b393f6996dd21230f1bcef637cb776b2f2ce01679beb2adc1fe19f6680cc748a0cb90aff70768801501f1dc56b21288d77e86948b"
        - name: SPRING_JWT_EXPIRATION_TIME
          value: "100000000000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8946
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8946
          initialDelaySeconds: 90
          periodSeconds: 20
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: auth-service-config
