apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: fintech
type: Opaque
stringData:
  username: "root"
  password: "password"
  url: "jdbc:mysql://my-database-instance.c122egeymo28.us-east-1.rds.amazonaws.com:3360/auth_service"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-credentials
  namespace: fintech
type: Opaque
stringData:
  jwt-secret: "6f872872a7e1dde2431f5f3b393f6996dd21230f1bcef637cb776b2f2ce01679beb2adc1fe19f6680cc748a0cb90aff70768801501f1dc56b21288d77e86948b"
  jwt-expiration: "100000000000"
